### PR TITLE
Register login

### LINKED ISSUE #15: User Log In
Made with Flask Login module

DOD: User is able to log in on previusly registered account

### PR DESCRIPTION
**Pull request by tomaszleszczynski1980**
Added login.
Also added flash messages showing in navbar as modals.

### CODE REVIEW

**Comment by roktiw** [comment]
Plese go with #18  and after you will close this PR, Gihtub will automatically close related ticket #15

**Comment by kMatejak** [comment]
When I am unlogged then page /add-event return flask-debugger page "TypeError: error() takes 0 positional arguments but 1 was given"

This is my fault - I forgot to add argument to function error.

**Comment by kMatejak** [comment]
We talked about it previosly (error after my try to upgrade my local db):  
```
ImportError: cannot import name 'db' from partially initialized module 'app' (most likely due to a circular import)
```  
```python
from models import *
```  
Models import must be below app initialization or otherwise we need to cut this initialization code to a separate file (\_\_init__.py or sth).  

I really do not know what is going on - on my machine it works like that. I will change it for sake of compatibility

**Comment by tomaszleszczynski1980** [comment]
errorhandler(401) bug fixed

**Comment by kMatejak** [comment]
> errorhandler(401) bug fixed 

gitted-out! thanks.

**Review by kMatejak — APPROVED** [review]

**Comment by kMatejak** [comment]
merged and resolved conflicts

**Pull request merged**
